GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/info/

### 

GET http://localhost:3001/api/persons/63d23a92527442fe51735dcc

###

DELETE http://localhost:3001/api/persons/63d242a86a0141ace98d30e0

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mike Murdock",
    "number": "111-333-222"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "111-333-222"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "111-333-222"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "No Number",
    "number": ""
}

### 

GET https://phonebook-backend-w5e9.onrender.com/api/persons

###

GET https://phonebook-backend-w5e9.onrender.com/api/persons/3

###

GET https://phonebook-backend-w5e9.onrender.com/info/

###

DELETE https://phonebook-backend-w5e9.onrender.com/api/persons/1

###

POST https://phonebook-backend-w5e9.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mike Murdock",
    "number": "111-333-222"
}

###

POST https://phonebook-backend-w5e9.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "111-333-222"
}

###

POST https://phonebook-backend-w5e9.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "111-333-222"
}

###

POST https://phonebook-backend-w5e9.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "No Number",
    "number": ""
}