GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/info/

### 

GET http://localhost:3001/api/persons/63d23a92527442fe51735dcc

### bad id

GET http://localhost:3001/api/persons/43

###

DELETE http://localhost:3001/api/persons/63d242a86a0141ace98d30e0

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mike Murdock",
    "number": "111-333-222"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "111-333-222"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Hola",
    "number": "111-333-222"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "No Number",
    "number": ""
}

### 

PUT http://localhost:3001/api/persons/63d2429d6a0141ace98d30de HTTP/1.1
content-type: application/json

{
    "name": "Clark Kent",
    "number": "73436745235364"
}

### short name

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Martinez",
    "number": "040-5544332211"
}